### ISSUE TITLE
Regexp based queries (e.g. contains, like, startsWith, endsWith) don't support multiline matches

### ISSUE THREAD

**Issue by jfrumar** [balderdashy/sails-mongo#220]
I am trying to query to check if an HTML email has already been sent, but the HTML body is too long to fit into a Regex (it throws an error). So I want to search a substring of the HTML (e.g. the first 1024 chars). The problem is that the Regex that's generated to query the DB doesn't support the multiline flag, and my HTML content isn't all on a single line:

https://github.com/balderdashy/sails-mongo/blob/master/lib%2Fquery%2Findex.js#L224

If I set the 'm' (multiline) flag it works. I will create a pull request for this, assuming I'm not missing a potential issue that this may cause?

**Comment by andyhu** [comment]
Why you need multi-line searches? I think the name `multi-line` search is a bit misleading, and you can simply use `/[\r\n]strings to search/` instead of `/^strings to search/m`. Actually if you add a `m` option, something will be wrong with `startsWith` and `endsWith`. Since a multi-line string like below will match it incorrectly.
If adds `m` option, `{startsWith: 'abc'}` will match
```
def
abc
ghi
```

**Comment by jfrumar** [comment]
Cool, I see the issue. I managed to solve my problem another way, so we can close this now.
