### ISSUE TITLE
Sails mongo blocking the event loop on BIG queries

### ISSUE THREAD

**Issue by akocmark** [balderdashy/sails-mongo#376]
Hi

Im using this library and sailsjs together, but for some reason when I tried querying 9,000 records at once the event loop is being blocked and other small requests were waiting for the first request to finish. 

Im running my app on aws ec2 t2.micro instance with 1gb ram. 

I know I should paginate the query for better performance but this is just a test to see whether this library is efficient to use along with sailsjs for nodejs-based apps. I think by using this library we're not using the full potential of nodejs.

Can anyone confirm if the blocking of the event loop was because of this library or it was on sailsjs core?

Thanks and Regards

**Comment by devinivy** [comment]
Sorry to answer a question with more questions, but can you give more information?  How long is the event loop being blocked?  What is the query that you're making, and are associations being used?  Could you possibly profile your app to see where the time is being spent?

**Comment by akocmark** [comment]
Hi devinivy,

Could it be possible that it has something to do with this pull request #369 ?

And for your questions;
1. the request takes around 19-24 seconds (all other request will not get served)

2. This is my query
```
    User.count({ status: 1 }).then(function (verified) {
      User.count({ status: 0 }).then(function (unverified) {
        User.find().exec(function (err, users) {
          if (err) {
            return res.send(500, { erorr: err });
          }

          return res.send(200, {
            users: users,
            verified: verified,
            unverified: unverified
          });
        });
      });
    });
```
3. No associations being used.

**Comment by devinivy** [comment]
@akocmark that PR is definitely related, but what's unclear is if the deserialization method is the main reason for blocking the event loop, or if there are other areas that are responsible.  I assume it's the `find()` query that's taking all the time.  Is that right?  The find query would use the deserialization method.  Perhaps you could test the same query using the sails-mongo branch in #369.

**Comment by stweedie** [comment]
In all honesty, Waterline blocks for a long time during its deserialization steps too. We have a fork that adjusts this (using the same concept as in the PR you mentioned), but I figured it would be much easier to introduce this small change first (because the Waterline change is larger). I will be submitting a PR to Waterline shortly, if this fixes the issue.

But the concept is the same. It is mainly the normalizeResults function in lib/utils that hogs the CPU. I've put together a very basic Sails application that demonstrates the change depicted in the PR.

https://github.com/stweedie/sails-mongo-test

The fork of Waterline I mentioned is at https://github.com/PetroCloud/waterline

**Comment by akocmark** [comment]
@stweedie 
Cool man! I will be using your fork of waterline and sails-mongo for the time being. Your background-compute library was awesome!

**Comment by particlebanana** [comment]
So right now the bottleneck is when Waterline gets 9000 results back it has to serialize and instrument 9000 models. This could be better but it's also going to slow. We have a stream interface that could be used so you could stream the records back instead of taking up the memory instrumenting all the models, which you wouldn't need.

It looks like @stweedie is doing some interesting work looking into that stuff and would love to hear more about the findings.
